Allow to gather environments list
dominodatalab/python-domino-environments pull request #2
Opened 2022-05-04 17:04 UTC by Dranaxel

As using the library I was really missing this feature

2022-07-22 16:54 UTC, mildmelon approved these changes
LGTM thanks for the PR

2022-07-22 16:59 UTC, mildmelon requested changes
One final thing we need to do before merging this PR is to update the version.

The version is located in `domino_environments/_version.py` and will propagate changes to `setup.py`

We need to update from `1.0.3` to `1.1.0`

2022-07-22 17:08 UTC, mildmelon requested changes
Just realized there are some semantic changes that I'd like to see.

2022-07-22 17:08 UTC, mildmelon commented on domino_environments/_environments.py
> +    def get_environments_list(self):
I would like to keep the method names consistent
```suggestion
    def environments_list(self):
```

2022-07-22 17:08 UTC, mildmelon commented on domino_environments/_environments.py
> +        url = self._routes.get_environments_list()
Updating the usage from prior change.
```suggestion
        url = self._routes.environments_list()
```

2022-07-23 10:07 UTC, Dranaxel commented
Hi @mildmelon thanks for your feedback, I totally understand the remarks. I will take some time to fix it this WE I hope

2022-09-12 20:15 UTC, mildmelon approved these changes
LGTM, thanks I'll merge now

2022-09-12 20:16 UTC, merged